module ProjectEuler where

import Control.Monad (forM) -- Used by answer79_1
import Data.Char (digitToInt) -- Used by answer8_1
import Data.List (
  transpose, -- Used by answer11_1
  tails, -- Used by answer8_1, answer11_1
  sort, -- Used by answer62_1
  permutations, -- Used by answer68_1
  nub, sortBy) -- Used by answer79_1
import Lib (rotate) -- Used by answer11_1
import Math (
  primes, -- Used by answer5_1, answer7_1
  primesBounded, -- Used by answer10_1
  numOfFactors, -- Used by answer12_1
  fact, -- Used by answer15_1
  pascalsTriangle) -- Used by answer15_3

-- Problem 1: Mutiple of 3 and 5
-- --
-- If we list all the natural numbers below 10 that are multiples of 3 or 5, we
-- get 3, 5, 6 and 9. The sum of these multiples is 23.
-- Find the sum of all the multiples of 3 or 5 below 1000.
-- --
-- Answer: 233168

-- answer1_1: O(1)
answer1_1 :: Integer
answer1_1 = sum' 3 + sum' 5 - sum' 15
  where numberOfItem limit x = limit `quot` x
        sum limit x = (x + noi * x) * noi `quot` 2
          where noi = numberOfItem limit x
        sum' = sum (1000 - 1)

-- answer1_2: O(n)
answer1_2 :: Integer
answer1_2 =
  sum [3, 6..999] + sum [5, 10..999] - sum [15, 30..999]

-- answer1_3: O(n)
answer1_3 :: Integer
answer1_3 = sum $
  filter (\x -> x `rem` 3 == 0 || x `rem` 5 == 0) [1..999]

-- Problem 2: Even Fibonacci numbers
-- --
-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:
--   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not
-- exceed four million, find the sum of the even- valued terms.
-- --
-- Answer: 4613732

-- answer2_1: O(n)
answer2_1 :: Integer
answer2_1 = loop 0 1 2
  where loop sum a b
          | a <= 4000000 = loop (sum + if even a then a else 0) b (a + b)
          | otherwise = sum

-- answer2_2: O(n)
answer2_2 :: Integer
answer2_2 = sum $ filter even $ takeWhile (<= 4000000) $ fib 1 2
  where fib a b = a : fib b (a + b)

-- Problem 3: Largest prime factor
-- --
-- The prime factors of 13195 are 5, 7, 13 and 29.
-- What is the largest prime factor of the number 600851475143 ?
-- --
-- Answer: 6857

-- answer3_1: O(n)
-- BUG 答案正确，所以懒得改了
answer3_1 :: Integer
answer3_1 = find num 2 2
  where num = 600851475143
        index = floor $ sqrt $ fromInteger num
        find x f r
          | f > index = r
          | x `rem` f == 0 = find (x `quot` f) (f + 1) f
          | otherwise = find x (f + 1) r

-- Problem 4: Largest palindrome product
-- --
-- A palindromic number reads the same both ways. The largest palindrome made
-- from the product of two 2-digit numbers is 9009 = 91 × 99.
-- Find the largest palindrome made from the product of two 3-digit numbers.
-- --
-- Answer: 906609

-- answer4_1: O(10^n)
answer4_1 :: Integer
answer4_1 = foldl max 0 $
            filter (\xs -> reverse (show xs) == show xs)
                   [x * y | x <- reverse [100..999],
                            y <- reverse [100..x]]

-- Problem 5: Smallest multiple
-- --
-- 2520 is the smallest number that can be divided by each of the numbers from
-- 1 to 10 without any remainder.
-- What is the smallest positive number that is evenly divisible by all of the
-- numbers from 1 to 20?
-- --
-- Answer: 232792560

-- answer5_1: O(?)
answer5_1 :: Integer
answer5_1 = product $
            map (\x -> last $ takeWhile (<= 20) $ map (x ^) [1..]) $
            takeWhile (<= 20) primes

-- Problem 6: Sum square difference
-- --
-- The sum of the squares of the first ten natural numbers is,
-- 12 + 22 + ... + 102 = 385
-- The square of the sum of the first ten natural numbers is,
-- (1 + 2 + ... + 10)2 = 552 = 3025
-- Hence the difference between the sum of the squares of the first ten natural
-- numbers and the square of the sum is 3025 − 385 = 2640.
-- Find the difference between the sum of the squares of the first one hundred
-- natural numbers and the square of the sum.
-- --
-- Answer: 25164150

-- answer6_1: O(?)
answer6_1 :: Integer
answer6_1 = sqr (sum [1..100]) - sum [sqr x | x <- [1..100]]
  where sqr x = x * x

-- Problem 7: 10001st prime
-- --
-- By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see
-- that the 6th prime is 13.
-- What is the 10 001st prime number?
-- --
-- Answer: 104743

-- answer7_1: O(?)
answer7_1 :: Integer
answer7_1 = primes !! 10000

-- Problem 8: Largest product in a series
-- --
-- The four adjacent digits in the 1000-digit number that have the greatest
-- product are 9 × 9 × 8 × 9 = 5832.
-- 73167176531330624919225119674426574742355349194934
-- 96983520312774506326239578318016984801869478851843
-- 85861560789112949495459501737958331952853208805511
-- 12540698747158523863050715693290963295227443043557
-- 66896648950445244523161731856403098711121722383113
-- 62229893423380308135336276614282806444486645238749
-- 30358907296290491560440772390713810515859307960866
-- 70172427121883998797908792274921901699720888093776
-- 65727333001053367881220235421809751254540594752243
-- 52584907711670556013604839586446706324415722155397
-- 53697817977846174064955149290862569321978468622482
-- 83972241375657056057490261407972968652414535100474
-- 82166370484403199890008895243450658541227588666881
-- 16427171479924442928230863465674813919123162824586
-- 17866458359124566529476545682848912883142607690042
-- 24219022671055626321111109370544217506941658960408
-- 07198403850962455444362981230987879927244284909188
-- 84580156166097919133875499200524063689912560717606
-- 05886116467109405077541002256983155200055935729725
-- 71636269561882670428252483600823257530420752963450
-- Find the thirteen adjacent digits in the 1000-digit number that have the
-- greatest product. What is the value of this product?
-- --
-- Answer: 23514624000

-- answer8_1: O(?)
answer8_1 :: Int
answer8_1 = foldl (\m -> max m . product . map digitToInt . take 13) 0 $
            takeWhile ((>= 13) . length) $ tails series
  where series = "73167176531330624919225119674426574742355349194934" ++
                 "96983520312774506326239578318016984801869478851843" ++
                 "85861560789112949495459501737958331952853208805511" ++
                 "12540698747158523863050715693290963295227443043557" ++
                 "66896648950445244523161731856403098711121722383113" ++
                 "62229893423380308135336276614282806444486645238749" ++
                 "30358907296290491560440772390713810515859307960866" ++
                 "70172427121883998797908792274921901699720888093776" ++
                 "65727333001053367881220235421809751254540594752243" ++
                 "52584907711670556013604839586446706324415722155397" ++
                 "53697817977846174064955149290862569321978468622482" ++
                 "83972241375657056057490261407972968652414535100474" ++
                 "82166370484403199890008895243450658541227588666881" ++
                 "16427171479924442928230863465674813919123162824586" ++
                 "17866458359124566529476545682848912883142607690042" ++
                 "24219022671055626321111109370544217506941658960408" ++
                 "07198403850962455444362981230987879927244284909188" ++
                 "84580156166097919133875499200524063689912560717606" ++
                 "05886116467109405077541002256983155200055935729725" ++
                 "71636269561882670428252483600823257530420752963450"

-- Problem 9: Special Pythagorean triplet
-- --
-- A Pythagorean triplet is a set of three natural numbers, a < b < c, for
-- which, a ^ 2 + b ^ 2 = c ^ 2
-- For example, 32 + 42 = 9 + 16 = 25 = 52.
-- There exists exactly one Pythagorean triplet for which a + b + c = 1000.
-- Find the product abc.
-- --
-- Answer: 31875000

-- answer9_1: O(?)
answer9_1 :: Integer
answer9_1 = let (a, b, c) = head $
                            filter (\(a, b, c) -> a * a + b * b == c * c)
                              [(a, b, 1000 - a - b) |
                                a <- [1..500], b <- [a..500]]
             in a * b * c

-- Problem 10: Summation of primes
-- --
-- The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
-- Find the sum of all the primes below two million.
-- --
-- Answer: 142913828922

-- answer10_1: O(?)
answer10_1 :: Integer
answer10_1 = sum $ primesBounded 2000000

-- Problem 11: Largest product in a grid
-- --
-- In the 20×20 grid below, four numbers along a diagonal line have been marked
-- in red.
-- 08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
-- 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
-- 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
-- 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
-- 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
-- 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
-- 32 98 81 28 64 23 67 10<26>38 40 67 59 54 70 66 18 38 64 70
-- 67 26 20 68 02 62 12 20 95<63>94 39 63 08 40 91 66 49 94 21
-- 24 55 58 05 66 73 99 26 97 17<78>78 96 83 14 88 34 89 63 72
-- 21 36 23 09 75 00 76 44 20 45 35<14>00 61 33 97 34 31 33 95
-- 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
-- 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
-- 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
-- 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
-- 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
-- 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
-- 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
-- 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
-- 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
-- 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
-- The product of these numbers is 26 × 63 × 78 × 14 = 1788696.
-- What is the greatest product of four adjacent numbers in the same direction
-- (up, down, left, right, or diagonally) in the 20×20 grid?
-- --
-- Answer: 70600674

-- answer11_1: O(?)
answer11_1 :: Integer
answer11_1 = maximum [vmax, hmax, lsmax, rsmax]
  where vmax = rowsMaxProduct grid
        hmax = rowsMaxProduct $ transpose grid
        lsmax = rowsMaxProduct $ rotate grid
        rsmax = rowsMaxProduct $ rotate $ reverse grid
        rowsMaxProduct = maximum .
                         concatMap (
                           map (product . take 4) .
                           filter ((>= 4) . length) . tails)
        grid =
          [
            [8, 2, 22,97,38,15, 0,40, 0,75, 4, 5, 7,78,52,12,50,77,91, 8],
            [49,49,99,40,17,81,18,57,60,87,17,40,98,43,69,48, 4,56,62, 0],
            [81,49,31,73,55,79,14,29,93,71,40,67,53,88,30, 3,49,13,36,65],
            [52,70,95,23, 4,60,11,42,69,24,68,56, 1,32,56,71,37, 2,36,91],
            [22,31,16,71,51,67,63,89,41,92,36,54,22,40,40,28,66,33,13,80],
            [24,47,32,60,99, 3,45, 2,44,75,33,53,78,36,84,20,35,17,12,50],
            [32,98,81,28,64,23,67,10,26,38,40,67,59,54,70,66,18,38,64,70],
            [67,26,20,68, 2,62,12,20,95,63,94,39,63, 8,40,91,66,49,94,21],
            [24,55,58, 5,66,73,99,26,97,17,78,78,96,83,14,88,34,89,63,72],
            [21,36,23, 9,75, 0,76,44,20,45,35,14, 0,61,33,97,34,31,33,95],
            [78,17,53,28,22,75,31,67,15,94, 3,80, 4,62,16,14, 9,53,56,92],
            [16,39, 5,42,96,35,31,47,55,58,88,24, 0,17,54,24,36,29,85,57],
            [86,56, 0,48,35,71,89, 7, 5,44,44,37,44,60,21,58,51,54,17,58],
            [19,80,81,68, 5,94,47,69,28,73,92,13,86,52,17,77, 4,89,55,40],
            [4, 52, 8,83,97,35,99,16, 7,97,57,32,16,26,26,79,33,27,98,66],
            [88,36,68,87,57,62,20,72, 3,46,33,67,46,55,12,32,63,93,53,69],
            [4, 42,16,73,38,25,39,11,24,94,72,18, 8,46,29,32,40,62,76,36],
            [20,69,36,41,72,30,23,88,34,62,99,69,82,67,59,85,74, 4,36,16],
            [20,73,35,29,78,31,90, 1,74,31,49,71,48,86,81,16,23,57, 5,54],
            [1, 70,54,71,83,51,54,69,16,92,33,48,61,43,52, 1,89,19,67,48]
          ]

-- Problem 12: Highly divisible triangular number
-- --
-- The sequence of triangle numbers is generated by adding the natural numbers.
-- So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
-- first ten terms would be:
-- 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
-- Let us list the factors of the first seven triangle numbers:
--     1: 1
--     3: 1,3
--     6: 1,2,3,6
--    10: 1,2,5,10
--    15: 1,3,5,15
--    21: 1,3,7,21
--    28: 1,2,4,7,14,28
-- We can see that 28 is the first triangle number to have over five divisors.
-- What is the value of the first triangle number to have over five hundred
-- divisors?
-- --
-- Answer: 76576500

-- answer12_1: O(?)
answer12_1 :: Integer
answer12_1 = loop 1 2
  where loop r x
          | numOfFactors r > 500 = r
          | otherwise = loop (r + x) (x + 1)

-- Problem 15: Lattice paths
-- --
-- Starting in the top left corner of a 2×2 grid, and only being able to move
-- to the right and down, there are exactly 6 routes to the bottom right
-- corner.
-- [https://projecteuler.net/project/images/p015.gif]
-- How many such routes are there through a 20×20 grid?
-- --
-- Answer: 137846528820

-- answer15_1: O(1)
answer15_1 :: Integer
answer15_1 = fact (20 * 2) `div` (fact 20 ^ 2)

-- answer15_2: O(?)
answer15_2 :: Integer
answer15_2 = cal 20 20
  where cal x y
          | x == 1 || y == 1 = toInteger $ x + y
          | x == y = 2 * mcal (x - 1) y
          | otherwise = mcal (x - 1) y + mcal x (y - 1)
        mcal x y
          | x < y = mcal y x
          | otherwise = mcall !! (x - 1) !! (y - 1)
        mcall = [[cal x y | y <- [1..x]] | x <- [1..20]]

-- answer15_3: O(?)
answer15_3 :: Integer
answer15_3 = pascalsTriangle !! 20 !! 20

-- Problem 60: Prime pair sets
-- --
-- The primes 3, 7, 109, and 673, are quite remarkable. By taking any two
-- primes and concatenating them in any order the result will always be prime.
-- For example, taking 7 and 109, both 7109 and 1097 are prime. The sum of
-- these four primes, 792, represents the lowest sum for a set of four primes
-- with this property.
-- Find the lowest sum for a set of five primes for which any two primes
-- concatenate to produce another prime.
-- --
-- Answer: ??

-- answer60_1: O(?)
-- I can't solve it yet now.
answer60_1 :: Integer
answer60_1 = undefined

-- Problem 62: Cubic permutations
-- --
-- The cube, 41063625 (345^3), can be permuted to produce two other cubes:
-- 56623104 (384^3) and 66430125 (405^3). In fact, 41063625 is the smallest
-- cube which has exactly three permutations of its digits which are also cube.
-- Find the smallest cube for which exactly five permutations of its digits are
-- cube.
-- --
-- Answer: 127035954683

-- andwer62_1: O(?)
answer62_1 :: String
answer62_1 = search 0 [] cubes
  where cubes = [(c, sort c) | x <- [1..], let c = show $ x * x * x]
        search x l cs @ ((n, c) : r)
          | length c > x = search (x + 1) [] cs
          | otherwise = let (nl, t, nr) = add c n l []
                         in if t == 5 then nr
                            else search x nl r
        add c n ((tu @ (c', n', t)) : r) res
          | c == c' = (r ++ (c', n', t + 1) : res, t + 1, n')
          | otherwise = add c n r (tu : res)
        add c n [] res = ((c, n, 1) : res, 1, "")

-- Problem 68: Magic 5-gon ring
-- --
-- Consider the following "magic" 3-gon ring, filled with the numbers 1 to 6,
-- and each line adding to nine.
-- [https://projecteuler.net/project/images/p068_1.gif]
-- Working clockwise, and starting from the group of three with the numerically
-- lowest external node (4,3,2 in this example), each solution can be described
-- uniquely. For example, the above solution can be described by the set:
-- 4,3,2; 6,2,1; 5,1,3.
-- It is possible to complete the ring with four different totals: 9, 10, 11,
-- and 12. There are eight solutions in total.
-- Total    Solution Set
--   9   4,2,3; 5,3,1; 6,1,2
--   9   4,3,2; 6,2,1; 5,1,3
--  10   2,3,5; 4,5,1; 6,1,3
--  10   2,5,3; 6,3,1; 4,1,5
--  11   1,4,6; 3,6,2; 5,2,4
--  11   1,6,4; 5,4,2; 3,2,6
--  12   1,5,6; 2,6,4; 3,4,5
--  12   1,6,5; 3,5,4; 2,4,6
-- By concatenating each group it is possible to form 9-digit strings; the
-- maximum string for a 3-gon ring is 432621513.
-- Using the numbers 1 to 10, and depending on arrangements, it is possible to
-- form 16- and 17-digit strings. What is the maximum 16-digit string for a
-- "magic" 5-gon ring?
-- [https://projecteuler.net/project/images/p068_2.gif]
-- --
-- Answer: 6531031914842725

-- answer68_1: O(?)
answer68_1 :: String
answer68_1 = concatMap (concatMap show . (\([o1, o2, o3, o4], [i1, i2, i3]) ->
               [6, 5, 3, o1, 3, i1, o2, i1, i2, o3, i2, i3, o4, i3, 5])) $
             filter (\([o1, o2, o3, o4], [i1, i2, i3]) ->
                      o1 + 3 + i1 == 14 && o2 + i1 + i2 == 14 &&
                      o3 + i2 + i3 == 14 && o4 + i3 + 5 == 14)
                    [(o, i) | o <- permutations [7, 8, 9, 10],
                              i <- permutations [1, 2, 4]]

-- Problem 79: Passcode derivation
-- --
-- A common security method used for online banking is to ask the user for
-- three random characters from a passcode. For example, if the passcode was
-- 531278, they may ask for the 2nd, 3rd, and 5th characters; the expected
-- reply would be: 317.
-- The text file, [https://projecteuler.net/project/resources/p079_keylog.txt],
-- contains fifty successful login attempts.
-- Given that the three characters are always asked for in order, analyse the
-- file so as to determine the shortest possible secret passcode of unknown
-- length.
-- --
-- Answer: 73162890

-- answer79_1: O(?)
answer79_1 :: IO String
answer79_1 = do
  kl <- forM [1..50] (const getLine)
  return $ sortBy (\c1 c2 ->
    foldl (\o [a, b, c] ->
            if c2 == a && (c1 == b || c1 == c) || c2 == b && c1 == c
            then GT else o)
          LT kl) $ nub $ concat kl

-- Problem 97: Large non-Mersenne prime
-- --
-- The first known prime found to exceed one million digits was discovered in
-- 1999, and is a Mersenne prime of the form 2 ^ 6972593 − 1; it contains
-- exactly 2,098,960 digits. Subsequently other Mersenne primes, of the form
-- 2 ^ p − 1, have been found which contain more digits.
-- However, in 2004 there was found a massive non-Mersenne prime which contains
-- 2,357,207 digits: 28433 × 2 ^ 7830457 + 1.
-- Find the last ten digits of this prime number.
-- --
-- Answer: 8739992577

-- answer97_1: O(1)
answer97_1 :: Integer
answer97_1 = (28433 * 2 ^ 7830457 + 1) `mod` 10000000000
